### ISSUE TITLE
[BUG] 更新flutter至1.12版本安装正式包闪退

### ISSUE THREAD

**Issue by JamesGZM** [befovy/fijkplayer#142]
**Describe the bug**
更新flutter 至 1.12之后
android 项目已经完成迁移

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:/Android/Sdk
    • Java binary at: D:\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\AndroidStudio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.40.2)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • ALP TL00 • NDF0218122001780 • android-arm64 • Android 9 (API 28)
**To Reproduce**
1. flutter clean 
2. flutter build apk
3. install and open release apk

**logcat**
2019-12-14 18:16:08.385 24690-24690/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xdtech.news.greatriver, PID: 24690
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.xdtech.news.greatriver-7qQHIBX9BszWey9FU3KFIg==/lib/arm/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1672)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a(Unknown Source:0)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(Unknown Source:18)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(Unknown Source:0)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source:13)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source:2)
        at c.c.a.a.<init>(Unknown Source:39)
        at c.c.a.b.a(Unknown Source:25)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:32)
        at com.example.flutter_jxnews.MainActivity.a(Unknown Source:5)
        at d.a.b.a.e.a(Unknown Source:64)
        at d.a.b.a.d.onCreate(Unknown Source:22)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**fijkplayer version**
0.2.3

**Smartphone (please complete the following information):**
 - Device: [HUAWEI mate10 HUAWEI 荣耀v20]
 - OS: [Android 9.0 android 10.0]

**Comment by befovy** [comment]
初步判断是混淆配置问题。
错误中 class 还有 IjkMediaPlayer 中的方法都成了 a ，b， c， d。

**Comment by JamesGZM** [comment]
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects  @befovy  参考这个迁移的 
没找到哪里有混淆文件

**Comment by befovy** [comment]
你的项目中有 
```
-keep class tv.danmaku.ijk.media.player.** {
    *;
} 
```
 吗？

参考 https://github.com/befovy/fijkplayer/pull/98/files

另外， example 文件夹中的项目你那边也会崩溃吗

**Comment by JamesGZM** [comment]
@befovy  没有这个混淆 之前没加所以没在意 我加上试一下 demo还没迁移到1.12尝试

**Comment by JamesGZM** [comment]
@befovy  加上混淆就好了
