### ISSUE TITLE
与flutterdownloader一起使用会APP闪退

### ISSUE THREAD

**Issue by mrdong916** [befovy/fijkplayer#154]
下面我的小米收集自己拦截到的闪退信息
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
	at com.befovy.fijkplayer.FijkPlugin.audioManager(FijkPlugin.java:370)
	at com.befovy.fijkplayer.FijkPlugin.<init>(FijkPlugin.java:140)
	at com.befovy.fijkplayer.FijkPlugin.registerWith(FijkPlugin.java:62)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:30)
	at xyz.a5in.a5yin.MusicApplication.registerWith(MusicApplication.java:25)
	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)


```

**Comment by befovy** [comment]
@mrdong916 Thanks.

@all-contributors please add @mrdong916  for bug
