### ISSUE TITLE
[BUG] Crashed in released apk

### ISSUE THREAD

**Issue by raphaelsoul** [befovy/fijkplayer#166]
**Describe the bug**

**To Reproduce**
debug真机调试正常 release构建安装后启动时立即闪退

**fijkplayer version**
fijkplayer 0.5.0
flutter sdk (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CN)

**Smartphone (please complete the following information):**
OnePlusA6010
Android 10

**Additional context**
```
01-10 11:33:40.498 22570 22570 E AndroidRuntime: FATAL EXCEPTION: main
01-10 11:33:40.498 22570 22570 E AndroidRuntime: Process: com.example.app, PID: 22570
01-10 11:33:40.498 22570 22570 E AndroidRuntime: java.lang.UnsatisfiedLinkError: JNI_OnLoad failed on a previous attempt to load "/data/app/com.example.app-ljEvtTNflm8vn_V6w-9s8g==/lib/arm64/libijksdl.so"
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1667)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a(Unknown Source:0)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(Unknown Source:18)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(Unknown Source:0)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source:13)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source:2)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at c.b.a.a.<init>(Unknown Source:39)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at c.b.a.b.a(Unknown Source:25)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:23)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at com.example.app.MainActivity.a(Unknown Source:5)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at d.a.b.a.e.a(Unknown Source:64)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at d.a.b.a.d.onCreate(Unknown Source:22)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7815)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7804)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7682)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
01-10 11:33:40.498 22570 22570 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
01-10 11:33:40.500  1300 22609 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-10 11:33:40.500  1300  5315 W ActivityTaskManager:   Force finishing activity com.example.app/.MainActivity
01-10 11:33:40.500  1300 22609 D FrameworkEventCollector: recordAppIssue PN: com.example.app
01-10 11:33:40.500  1300  5315 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{2423bbb token=Token{190e04a ActivityRecord{9fe11b5 u0 net.oneplus.launcher/.Launcher t2981}}} pkgName net.oneplus.launcher
01-10 11:33:40.500  1300  6454 D gwy     : OS Event: crash

```

**Comment by raphaelsoul** [comment]
#142

**Comment by befovy** [comment]
yes.  Same as #142
