### ISSUE TITLE
Error After Build apk release and when install cannot open app

### ISSUE THREAD

**Issue by saiko123** [befovy/fijkplayer#178]
java.lang.UnsatisfiedLinkError: JNI_OnLoad failed on a previous attempt to load "/data/app/com.mmapplab.livevideoplayer-lRjbspMF5KHUi4zDRugC1Q==/lib/arm64/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a(Unknown Source:0)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(Unknown Source:18)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(Unknown Source:0)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source:13)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source:2)
        at b.a.a.a.<init>(Unknown Source:39)
        at b.a.a.b.a(Unknown Source:25)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:11)
        at com.mmapplab.livevideoplayer.MainActivity.a(Unknown Source:5)
        at c.a.b.a.e.a(Unknown Source:64)
        at c.a.b.a.d.onCreate(Unknown Source:22)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2020-02-19 19:35:50.392 2722-2779/? E/Launcher.Utilities: getCurrentWallpaper error, e=java.lang.SecurityException: read wallpaper: Neither user 10037 nor current process has android.permission.READ_EXTERNAL_STORAGE.
2020-02-19 19:35:50.395 2722-2779/? E/Launcher.Utilities: getCurrentWallpaper error, e=java.lang.SecurityException: read wallpaper: Neither user 10037 nor current process has android.permission.READ_EXTERNAL_STORAGE.
2020-02-19 19:35:50.397 2722-2779/? E/Launcher.Utilities: getCurrentWallpaper error, e=java.lang.SecurityException: read wallpaper: Neither user 10037 nor current process has android.permission.READ_EXTERNAL_STORAGE.
2020-02-19 19:35:50.428 2722-2840/? E/Launcher.Utilities: getCurrentWallpaper error, e=java.lang.SecurityException: read wallpaper: Neither user 10037 nor current process has android.permission.READ_EXTERNAL_STORAGE.
2020-02-19 19:35:50.696 2722-2722/? E/Launcher: changeViewByFsGestureState,  view=FitSystemWindowView,  alpha=1.0,  scale=1.0
2020-02-19 19:35:50.696 2722-2722/? E/Launcher: changeViewByFsGestureState,  view=ShortcutMenuLayer,  alpha=1.0,  scale=1.0
2020-02-19 19:35:51.065 21895-21960/? E/SystemUpdate-ConnectionRSA: get key exception : com.android.org.bouncycastle.util.encoders.DecoderException: unable to decode base64 string: invalid characters encountered in base64 data
2020-02-19 19:35:51.727 697-3079/? E/ANDR-PERF-MPCTL: poll() has timed out for /sys/module/msm_performance/events/cpu_hotplug
2020-02-19 19:35:51.727 697-3079/? E/ANDR-PERF-MPCTL: Block on poll()
2020-02-19 19:35:52.140 21971-21971/? E/livevideoplaye: Not starting debugger since process cannot load the jdwp agent.
2020-02-19 19:35:52.369 21971-21971/? E/J4A: J4A_FindClass__catchAll: failed
2020-02-19 19:35:52.369 21971-21971/? E/J4A: J4A_FindClass__asGlobalRef__catchAll: failed: tv/danmaku/ijk/media/player/misc/IMediaDataSource
2020-02-19 19:35:52.375 21971-21971/? E/AndroidRuntime: FATAL EXCEPTION: main

**Comment by befovy** [comment]
keep java class in proguard file
see https://github.com/befovy/fijkplayer/pull/98/files

**Comment by saiko123** [comment]
Thanks befovy, it is work and you are soo cool.. I love it. and I appreciate. 👍
