### ISSUE TITLE
调用音量调节的接口时，功能正常，但日志会输出错误[BUG]

### ISSUE THREAD

**Issue by SpanishOnion** [befovy/fijkplayer#180]
**Describe the bug**
调用音量调节的接口功能正常，但日志会输出错误，每调用一次就会输出一次错误日志。

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
一行代码，不知道怎么尝试。

**To Reproduce**
问题的复现步骤
1. 代码调用：
 `FijkVolume.setVol(0.1)`
2. 错误如下：

```
E/MethodChannel#befovy.com/fijk(27667): Failed to handle method call
E/MethodChannel#befovy.com/fijk(27667): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
E/MethodChannel#befovy.com/fijk(27667):         at com.befovy.fijkplayer.FijkPlugin.onMethodCall(FijkPlugin.java:275)
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#befovy.com/fijk(27667):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#befovy.com/fijk(27667):         at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#befovy.com/fijk(27667):         at android.os.Looper.loop(Looper.java:175)
E/MethodChannel#befovy.com/fijk(27667):         at android.app.ActivityThread.main(ActivityThread.java:7625)
E/MethodChannel#befovy.com/fijk(27667):         at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#befovy.com/fijk(27667):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#befovy.com/fijk(27667):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/DartMessenger(27667): Uncaught exception in binary message listener
E/DartMessenger(27667): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(27667):         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/DartMessenger(27667):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:249)
E/DartMessenger(27667):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/DartMessenger(27667):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/DartMessenger(27667):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(27667):         at android.os.MessageQueue.next(MessageQueue.java:386)
E/DartMessenger(27667):         at android.os.Looper.loop(Looper.java:175)
E/DartMessenger(27667):         at android.app.ActivityThread.main(ActivityThread.java:7625)
E/DartMessenger(27667):         at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(27667):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/DartMessenger(27667):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
V/AudioManager(27667): getStreamMaxVolume  treamType: 3
V/AudioManager(27667): getStreamVolume  streamType: 3 volume: 5
V/AudioManager(27667): getStreamMaxVolume  treamType: 3
V/AudioManager(27667): setStreamVolume  streamType : 3  index: 5  flags: 0
I/AudioManager(27667): setStreamVolume streamType:3index:5flags:0
E/MethodChannel#befovy.com/fijk(27667): Failed to handle method call
E/MethodChannel#befovy.com/fijk(27667): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
E/MethodChannel#befovy.com/fijk(27667):         at com.befovy.fijkplayer.FijkPlugin.onMethodCall(FijkPlugin.java:275)
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#befovy.com/fijk(27667):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#befovy.com/fijk(27667):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#befovy.com/fijk(27667):         at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#befovy.com/fijk(27667):         at android.os.Looper.loop(Looper.java:175)
E/MethodChannel#befovy.com/fijk(27667):         at android.app.ActivityThread.main(ActivityThread.java:7625)
E/MethodChannel#befovy.com/fijk(27667):         at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#befovy.com/fijk(27667):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#befovy.com/fijk(27667):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/DartMessenger(27667): Uncaught exception in binary message listener
E/DartMessenger(27667): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(27667):         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/DartMessenger(27667):         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:249)
E/DartMessenger(27667):         at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/DartMessenger(27667):         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/DartMessenger(27667):         at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(27667):         at android.os.MessageQueue.next(MessageQueue.java:386)
E/DartMessenger(27667):         at android.os.Looper.loop(Looper.java:175)
E/DartMessenger(27667):         at android.app.ActivityThread.main(ActivityThread.java:7625)
E/DartMessenger(27667):         at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(27667):         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/DartMessenger(27667):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
V/AudioManager(27667): getStreamMaxVolume  treamType: 3
V/AudioManager(27667): getStreamVolume  streamType: 3 volume: 5
V/AudioManager(27667): getStreamMaxVolume  treamType: 3
V/AudioManager(27667): setStreamVolume  streamType : 3  index: 5  flags: 0
I/AudioManager(27667): setStreamVolume streamType:3index:5flags:0

```

**Expected behavior**
描述清楚你希望的运行结果是什么
不输出错误日志

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer
0.5.0  和 0.5.1 均有此错误

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
 - Device: [e.g. 华为 JSN-AL00a]
 - OS: [e.g. Android 9]

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.239], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

**Comment by befovy** [comment]
谢谢你的反馈。这个issue 描述很清楚，会优先处理

**Comment by befovy** [comment]
version 0.5.2 has fixed this bug

**Comment by SpanishOnion** [comment]
感谢大佬的火速修复！😁

**Comment by befovy** [comment]
@all-contributors please add @SpanishOnion  for bug
