### ISSUE TITLE
关于全屏问题

### ISSUE THREAD

**Issue by WuZhuoYu** [befovy/fijkplayer#247]
你好，我在开发使用过程中出现一个问题。
我是用flutter module 构建的项目，使用aar方式引入到Android 原生，点击全屏就会出现崩溃情况，请问是我什么没做的吗？
报错日志：
` java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
        at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:554)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.markTextureFrameAvailable(FlutterRenderer.java:274)
        at io.flutter.embedding.engine.renderer.FlutterRenderer.access$300(FlutterRenderer.java:38)
        at io.flutter.embedding.engine.renderer.FlutterRenderer$SurfaceTextureRegistryEntry$1.onFrameAvailable(FlutterRenderer.java:145)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5438)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)`

麻烦你看一下，谢谢

**Comment by befovy** [comment]
我还没有尝试过这种构建使用方式，可以提供一个 demo 吗
