### ISSUE TITLE
[BUG] 加急兄弟！null指针问题

### ISSUE THREAD

**Issue by deepface1990** [befovy/fijkplayer#272]
进入视频页开始play
马上退出，play release 就crash

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.befovy.fijkplayer.FijkPlugin.audioManager(FijkPlugin.java:584)
        at com.befovy.fijkplayer.FijkPlugin.requestAudioFocus(FijkPlugin.java:526)
        at com.befovy.fijkplayer.FijkPlugin.audioFocus(FijkPlugin.java:576)
        at com.befovy.fijkplayer.FijkPlayer.onStateChanged(FijkPlayer.java:186)
        at com.befovy.fijkplayer.FijkPlayer.handleEvent(FijkPlayer.java:226)
        at com.befovy.fijkplayer.FijkPlayer.onEvent(FijkPlayer.java:321)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$EventHandler.handleMessage(Unknown Source:51)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by befovy** [comment]
什么版本有这个 crash bug 的？

**Comment by befovy** [comment]
release version 0.8.6

**Comment by deepface1990** [comment]
复现场景是这样：进入首页，此时只有1个页面，跳转到视频页，方式是replace，然后再退出视频就会崩溃
