### ISSUE TITLE
[BUG] - Can not streaming 

### ISSUE THREAD

**Issue by ProFive** [befovy/fijkplayer#313]
Dear all, 
Sometimes can not streaming and found in the log 

```
W/System.err( 7135): java.lang.IllegalStateException
W/System.err( 7135): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
W/System.err( 7135): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2632)
I/IJKMEDIA( 7135): SDL_AMediaCodecJava_dequeueOutputBuffer: Exception

```

**Comment by huangsir0** [comment]
same.  any update?
